"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰀘"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000
[palettes.eldritch]
rosewater = "#F16C75" # Xresources color8/9/15 (pinkish red)
flamingo = "#F16C75"  # same as rosewater (no distinct alternate)
pink = "#A48CF2"      # Xresources color14 (purple mauve-ish)
mauve = "#7081D0"     # Xresources color13 (lavender blue)
red = "#F16C75"       # same red tone
maroon = "#8386A8"    # Xresources color4 (grayish blue)
peach = "#F7C67F"     # Xresources color10 (yellow-orange)
yellow = "#F1FC79"    # Xresources color11 (bright yellow)
green = "#04D1F9"     # Xresources color12 (bright blueish teal)
teal = "#3B4261"      # Xresources color3 (dark blue-gray)
sky = "#ABB4DA"       # Xresources color5 (light blue gray)
sapphire = "#89b4fa"  # fallback catppuccin blue tone
blue = "#89b4fa"      # fallback catppuccin blue tone
lavender = "#8386A8"  # Xresources color4 again (grayish blue)
text = "#ABB4DA"      # Xresources color5 (foreground)
subtext1 = "#8386A8"  # Xresources color4 (grayish)
subtext0 = "#3B4261"  # Xresources color3 (dark gray blue)
overlay2 = "#212337"  # Xresources color2 (dark slate)
overlay1 = "#191A21"  # Xresources color1 (very dark)
overlay0 = "#171928"  # Xresources color0 (background)
surface2 = "#3B4261"  # Xresources color3 (dark slate)
surface1 = "#212337"  # Xresources color2
surface0 = "#191A21"  # Xresources color1
base = "#171928"      # background (same as color0)
mantle = "#171928"    # same as base
crust = "#171928"     # same as base
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
[palettes.everforest]
rosewater = "#d699b6"
flamingo = "#dbbc7f"
pink = "#e69875"
mauve = "#a7c080"
red = "#7fbbb3"
maroon = "#e67e80"
peach = "#dbbc7f"
yellow = "#83c092"
green = "#dbbc7f"
teal = "#94e2d5"
sky = "#83c092"
sapphire = "#83c092"
blue = "#a7c080"
lavender = "#d699b6"
text = "#d3c6aa"
subtext1 = "#4a5258"
subtext0 = "#ddd0b4"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#2b3339"
mantle = "#24273a"
crust = "#181926"
[palettes.tokyo_night]
rosewater = "#f7768e"
flamingo = "#ff9e64"
pink = "#bb9af7"
mauve = "#bb9af7"
red = "#f7768e"
maroon = "#ff9e64"
peach = "#ff9e64"
yellow = "#9ece6a"
green = "#9ece6a"
teal = "#73daca"
sky = "#2ac3de"
sapphire = "#0db9d7"
blue = "#2ac3de"
lavender = "#b4f9f8"
text = "#a9b1d6"
subtext1 = "#787c99"
subtext0 = "#cbccd1"
overlay2 = "#444b6a"
overlay1 = "#2ac3de"
overlay0 = "#0db9d7"
surface2 = "#444b6a"
surface1 = "#2ac3de"
surface0 = "#1a1b26"
base = "#1a1b26"
mantle = "#1a1b26"
crust = "#1a1b26"
[palettes.carbon]
rosewater = "#FF7EB6"
flamingo = "#BE95FF"
pink = "#FF7EB6"
mauve = "#BE95FF"
red = "#78A9FF"
maroon = "#78A9FF"
peach = "#FF7EB6"
yellow = "#3DDBD9"
green = "#25be6a"
teal = "#08BDBA"
sky = "#3DDBD9"
sapphire = "#33B1FF"
blue = "#78A9FF"
lavender = "#F2F4F8"
text = "#f2f4f8"
subtext1 = "#e0e0e0"
subtext0 = "#525253"
overlay2 = "#3b3b3b"
overlay1 = "#33B1FF"
overlay0 = "#FF7EB6"
surface2 = "#3b3b3b"
surface1 = "#3DDBD9"
surface0 = "#161616"
base = "#161616"
mantle = "#161616"
crust = "#161616"
# add_newline = false
# # A minimal left prompt
# format = """$directory$character"""
# palette = "catppuccin_mocha"
# # move the rest of the prompt to the right
# right_format = """$all"""
# command_timeout = 1000
#
# [character]
# # λ
# # vicmd_symbol = "[N] >>>"
# # success_symbol = '[➜ :](bold green)'
# success_symbol = '[λ](bold green)'
#
# [directory.substitutions]
# '~/tests/starship-custom' = 'work-project'
#
# [git_branch]
# format = '[$symbol$branch(:$remote_branch)]($style)'
#
# [aws]
# format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
# disabled = false
# style = 'bold blue'
# symbol = " "
#
# [golang]
# format = '[ ](bold cyan)'
#
# [rust]
# format = '[ ](bold #ff6347)'
#
# [kubernetes]
# symbol = '☸ '
# disabled = true
# detect_files = ['Dockerfile']
# format = '[$symbol$context( \($namespace\))]($style) '
# contexts = [
#   { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
# ]
#
# [docker_context]
# disabled = true
#
# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
