[config]
reload_apps = true

[config.reload_apps_list]
kitty = true
gtk_theme = true

# [config.wallpaper]
# command = "swww"
# arguments = [
#   "img",
#   "-t",
#   "outer",
#   "--transition-duration",
#   "1.5",
#   "--transition-step",
#   "255",
#   "--transition-fps",
#   "60",
#   "-f",
#   "Nearest",
# ]
set = true
[templates.nvim]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-dark.lua'

[templates.pywal]
input_path = "~/.config/matugen/templates/pywal-colors"
output_path = "~/.cache/wal/colors"

[templates.yazi]
input_path = "~/.config/matugen/templates/colors-yazi.toml"
output_path = "~/.config/yazi/theme.toml"
# [templates.pywaljson]
# input_path = "~/.config/matugen/templates/pywal-colors.json"
# output_path = "~/.cache/wal/colors.json"
# post_hook = "pywalfox update &"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "killall -SIGUSR1 kitty &"

[templates.pywalsh]
input_path = "~/.config/matugen/templates/colors.sh"
output_path = "~/.cache/wal/colors.sh"
post_hook = "walogram -B > /dev/null 2>&1 &"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/hyprcolors.conf"

[templates.fuzzel-colors]
input_path = "~/.config/matugen/templates/fuzzel-colors.ini"
output_path = "~/.config/fuzzel/fuzzel.ini"

[templates.quickshell-colors]
input_path = "~/.config/matugen/templates/quickshell-colors.qml"
output_path = "~/.config/quickshell/kurumibar/Data/Colors.qml"
# post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
